"""Build the app's translations from the Android app's.

Every English text in ui/renderer that is word for word an English string of
the Android app (res/values/strings.xml) gets that string's translation from
res/values-<lang>/strings.xml. The rest stays English until someone adds it
by hand to ui/renderer/i18n/extra/<lang>.json (English -> translation).

  python ui/tools/i18n.py <android app>/app/src/main/res ui/renderer

The Android strings are Apache-2.0 (Rethink DNS + Firewall, AuroraVPN).
"""
import glob
import html
import json
import os
import re
import sys

NAMES = {
    'ar': 'العربية', 'az': 'Azərbaycanca', 'be': 'Беларуская', 'bg': 'Български', 'bn': 'বাংলা',
    'cs': 'Čeština', 'da': 'Dansk', 'de': 'Deutsch', 'el': 'Ελληνικά', 'es': 'Español', 'fa': 'فارسی',
    'fi': 'Suomi', 'fr': 'Français', 'hi': 'हिन्दी', 'hu': 'Magyar', 'in': 'Bahasa Indonesia',
    'it': 'Italiano', 'iw': 'עברית', 'ja': '日本語', 'ko': '한국어', 'lt': 'Lietuvių', 'lv': 'Latviešu',
    'ml': 'മലയാളം', 'nb-rNO': 'Norsk bokmål', 'nl': 'Nederlands', 'or': 'ଓଡ଼ିଆ', 'pl': 'Polski',
    'pt': 'Português', 'pt-rBR': 'Português (Brasil)', 'ro': 'Română', 'ru': 'Русский', 'si': 'සිංහල',
    'sk': 'Slovenčina', 'sr': 'Српски', 'sv': 'Svenska', 'sw': 'Kiswahili', 'ta': 'தமிழ்', 'th': 'ไทย',
    'tl': 'Tagalog', 'tr': 'Türkçe', 'uk': 'Українська', 'ur': 'اردو', 'uz': 'Oʻzbekcha',
    'vi': 'Tiếng Việt', 'zh-rCN': '简体中文', 'zh-rHK': '繁體中文 (香港)', 'zh-rTW': '繁體中文 (台灣)',
}
RTL = {'ar', 'fa', 'iw', 'ur'}
MIN_STRINGS = 40  # leave out languages with fewer translated texts than this


def android_strings(path):
    out = {}
    s = open(path, encoding='utf-8').read()
    for m in re.finditer(r'<string name="([^"]+)"([^>]*)>(.*?)</string>', s, re.S):
        if 'translatable="false"' in m.group(2):
            continue
        v = re.sub(r'<!\[CDATA\[(.*?)\]\]>', r'\1', m.group(3), flags=re.S)
        v = html.unescape(re.sub(r'<[^>]+>', '', v))
        v = v.replace("\\'", "'").replace('\\"', '"').replace('\\n', ' ').strip()
        if v.startswith('"') and v.endswith('"'):
            v = v[1:-1]
        out[m.group(1)] = v
    return out


def ui_texts(d):
    found = set()
    files = glob.glob(os.path.join(d, '*.js')) + glob.glob(os.path.join(d, '*.html'))
    for f in files:
        if os.path.basename(f) in ('icons.js', 'data.js'):
            continue
        s = open(f, encoding='utf-8').read()
        for m in re.finditer(r"'((?:[^'\\\n]|\\.)*)'|\"((?:[^\"\\\n]|\\.)*)\"|>([^<>{}\n]+)<", s):
            t = (m.group(1) or m.group(2) or m.group(3) or '').strip()
            if len(t) > 1 and re.search(r'[A-Za-z]{2}', t):
                found.add(t)
    return found


def main():
    res, renderer = sys.argv[1], sys.argv[2]
    out_dir = os.path.join(renderer, 'i18n')
    os.makedirs(out_dir, exist_ok=True)
    en = android_strings(os.path.join(res, 'values', 'strings.xml'))
    keys_by_text = {}
    for k, v in en.items():
        keys_by_text.setdefault(v.lower(), []).append(k)
    wanted = {t: keys_by_text[t.lower()] for t in ui_texts(renderer) if t.lower() in keys_by_text}
    langs = []
    for d in sorted(glob.glob(os.path.join(res, 'values-*'))):
        code = os.path.basename(d)[len('values-'):]
        f = os.path.join(d, 'strings.xml')
        if code not in NAMES or not os.path.exists(f):
            continue
        tr = android_strings(f)
        table = {}
        for text, keys in wanted.items():
            for k in keys:
                if tr.get(k) and tr[k] != en[k]:
                    table[text] = tr[k]
                    break
        extra = os.path.join(out_dir, 'extra', code + '.json')
        if os.path.exists(extra):
            table.update(json.load(open(extra, encoding='utf-8')))
        if len(table) < MIN_STRINGS:
            continue
        body = json.dumps(table, ensure_ascii=False, indent=0, sort_keys=True)
        with open(os.path.join(out_dir, code + '.js'), 'w', encoding='utf-8', newline='\n') as w:
            w.write('// Generated by ui/tools/i18n.py from the Android app\'s translations (Apache-2.0).\n')
            w.write(f'i18nLoaded({json.dumps(code)}, {body});\n')
        langs.append([code, NAMES[code], len(table), code in RTL])
    with open(os.path.join(out_dir, 'languages.js'), 'w', encoding='utf-8', newline='\n') as w:
        w.write('// Generated by ui/tools/i18n.py: [code, name, translated texts, right-to-left].\n')
        w.write("'use strict';\n\nconst LANGUAGES = " + json.dumps(langs, ensure_ascii=False) + ';\n')
        w.write(f'const I18N_TOTAL = {len(wanted)};\n')
    print(f'{len(wanted)} texts shared with Android; {len(langs)} languages written')


main()
